=== Echtzeitsysteme/gips-examples/org.emoflon.gips.gipsl.examples.sdr.extended/resources/json/sdr-input-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "cores": {
            "type": "integer"
        },
        "threadsPerCore": {
            "type": "integer"
        },
        "interThreadCommunicationFactor": {
            "type": "number"
        },
        "blocks": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "complextity": {
                            "type": "number"
                        },
                        "inToOut": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "id",
                        "complextity",
                        "inToOut"
                    ]
                }
            ]
        },
        "flows": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "sourceId": {
                            "type": "integer"
                        },
                        "targetId": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "sourceId",
                        "targetId"
                    ]
                }
            ]
        }
    },
    "required": [
        "cores",
        "threadsPerCore",
        "interThreadCommunicationFactor",
        "blocks",
        "flows"
    ]
}

=== Echtzeitsysteme/gips-examples/org.emoflon.gips.gipsl.examples.sdr.extended/resources/json/sdr-example-input-data2.json
{
    "cores": 2,
    "threadsPerCore": 1,
    "interThreadCommunicationFactor": 0.25,
    "blocks": [
        {
            "id": 1,
            "complexity": 10.0,
            "inToOut": 1.0
        },
        {
            "id": 2,
            "complexity": 10.0,
            "inToOut": 1.0
        },
        {
            "id": 3,
            "complexity": 10.0,
            "inToOut": 1.0
        },
        {
            "id": 4,
            "complexity": 10.0,
            "inToOut": 1.0
        }
    ],
    "flows": [
        {
            "sourceId": 1,
            "targetId": 2
        },
        {
            "sourceId": 2,
            "targetId": 3
        },
        {
            "sourceId": 3,
            "targetId": 4
        }
    ]
}
